// frontend/src/components/BookingFlow/Step6Payment.jsx
import React, { useState, useEffect } from 'react';
import { loadStripe } from '@stripe/stripe-js';
import { Elements, CardElement, useStripe, useElements } from '@stripe/react-stripe-js';
import { CreditCard, Lock, Loader, CheckCircle, AlertCircle, Mail, Phone, User } from 'lucide-react';
import { validateEmail, validatePhone, formatPhoneNumber, formatCurrency } from '../../utils/validation';
import { api } from '../../services/api';

// Initialize Stripe
const stripePromise = loadStripe(import.meta.env.VITE_STRIPE_PUBLIC_KEY || 'pk_test_placeholder');

const CARD_ELEMENT_OPTIONS = {
  style: {
    base: {
      fontSize: '16px',
      color: '#1f2937',
      fontFamily: 'Inter, system-ui, sans-serif',
      '::placeholder': {
        color: '#9ca3af',
      },
    },
    invalid: {
      color: '#dc2626',
      iconColor: '#dc2626',
    },
  },
};

const PaymentForm = ({ formData, updateCustomerInfo, prevStep, setError, resetForm }) => {
  const stripe = useStripe();
  const elements = useElements();
  
  const [isProcessing, setIsProcessing] = useState(false);
  const [paymentSuccess, setPaymentSuccess] = useState(false);
  const [bookingId, setBookingId] = useState(null);
  
  const [customerInfo, setCustomerInfo] = useState({
    name: formData.customerInfo?.name || '',
    email: formData.customerInfo?.email || '',
    phone: formData.customerInfo?.phone || '',
  });
  
  const [errors, setErrors] = useState({});
  const [cardComplete, setCardComplete] = useState(false);

  const handleCustomerInfoChange = (field, value) => {
    setCustomerInfo((prev) => ({
      ...prev,
      [field]: field === 'phone' ? formatPhoneNumber(value) : value,
    }));
    
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: '' }));
    }
  };

  const validateCustomerInfo = () => {
    const newErrors = {};

    if (!customerInfo.name || customerInfo.name.trim().length < 2) {
      newErrors.name = 'Please enter your full name';
    }

    const emailError = validateEmail(customerInfo.email);
    if (emailError) {
      newErrors.email = emailError;
    }

    const phoneError = validatePhone(customerInfo.phone);
    if (phoneError) {
      newErrors.phone = phoneError;
    }

    return newErrors;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    // Validate customer info
    const validationErrors = validateCustomerInfo();
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    if (!stripe || !elements || !cardComplete) {
      setError('Please complete your payment information');
      return;
    }

    setIsProcessing(true);
    setError(null);

    try {
      // 1. Create booking in backend
      const bookingData = {
        ...formData,
        customerInfo,
        totalAmount: formData.estimate.total,
      };

      const bookingResult = await api.createBooking(bookingData);
      const newBookingId = bookingResult.bookingId;
      setBookingId(newBookingId);

      // 2. Create payment intent
      const paymentIntentResult = await api.createPaymentIntent(
        newBookingId,
        formData.estimate.total
      );

      const clientSecret = paymentIntentResult.clientSecret;

      // 3. Confirm payment with Stripe
      const cardElement = elements.getElement(CardElement);
      const { error, paymentIntent } = await stripe.confirmCardPayment(clientSecret, {
        payment_method: {
          card: cardElement,
          billing_details: {
            name: customerInfo.name,
            email: customerInfo.email,
            phone: customerInfo.phone,
          },
        },
      });

      if (error) {
        throw new Error(error.message);
      }

      // 4. Confirm payment in backend
      await api.confirmPayment(paymentIntent.id, newBookingId);

      // Success!
      setPaymentSuccess(true);
      
      // Save customer info
      updateCustomerInfo('name', customerInfo.name);
      updateCustomerInfo('email', customerInfo.email);
      updateCustomerInfo('phone', customerInfo.phone);

    } catch (err) {
      setError(err.message || 'Payment failed. Please try again.');
      console.error('Payment error:', err);
    } finally {
      setIsProcessing(false);
    }
  };

  if (paymentSuccess) {
    return (
      <div className="card animate-fade-in">
        <div className="text-center py-8">
          <div className="inline-flex items-center justify-center w-20 h-20 bg-green-100 rounded-full mb-6">
            <CheckCircle className="w-12 h-12 text-green-600" />
          </div>
          
          <h2 className="text-3xl font-bold text-gray-900 mb-3">
            Booking Confirmed! 🎉
          </h2>
          
          <p className="text-lg text-gray-600 mb-6">
            Your junk removal is scheduled and paid for.
          </p>

          <div className="bg-gray-50 rounded-lg p-6 mb-6 text-left max-w-md mx-auto">
            <h3 className="font-semibold text-gray-900 mb-3">Booking Details</h3>
            <div className="space-y-2 text-sm">
              <p><strong>Booking ID:</strong> {bookingId}</p>
              <p><strong>Amount Paid:</strong> {formatCurrency(formData.estimate.total)}</p>
              <p><strong>Email:</strong> {customerInfo.email}</p>
              <p><strong>Phone:</strong> {customerInfo.phone}</p>
            </div>
          </div>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6 text-left max-w-md mx-auto">
            <div className="flex gap-3">
              <Mail className="w-5 h-5 text-blue-600 mt-0.5" />
              <div className="text-sm text-blue-900">
                <p className="font-medium mb-1">Confirmation Sent</p>
                <p className="text-blue-800">
                  We've sent a confirmation email to <strong>{customerInfo.email}</strong> with all your booking details.
                  We'll also send a reminder 24 hours before your appointment.
                </p>
              </div>
            </div>
          </div>

          <button
            onClick={resetForm}
            className="btn-primary"
          >
            Book Another Pickup
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="card animate-fade-in">
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="bg-primary-100 p-2 rounded-lg">
            <CreditCard className="w-6 h-6 text-primary-600" />
          </div>
          <h2 className="text-2xl font-bold text-gray-900">Payment Details</h2>
        </div>
        <p className="text-gray-600">
          Complete your booking with secure payment.
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Amount Due */}
        <div className="bg-primary-50 border-2 border-primary-200 rounded-lg p-5">
          <div className="flex justify-between items-center">
            <span className="text-lg font-medium text-gray-900">Amount Due</span>
            <span className="text-3xl font-bold text-primary-600">
              {formatCurrency(formData.estimate.total)}
            </span>
          </div>
        </div>

        {/* Customer Information */}
        <div className="space-y-4">
          <h3 className="font-semibold text-gray-900">Contact Information</h3>
          
          <div>
            <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-2">
              <User className="inline w-4 h-4 mr-1" />
              Full Name
            </label>
            <input
              type="text"
              id="name"
              value={customerInfo.name}
              onChange={(e) => handleCustomerInfoChange('name', e.target.value)}
              placeholder="John Doe"
              disabled={isProcessing}
              className="input-field"
            />
            {errors.name && (
              <div className="error-message">
                <AlertCircle className="w-4 h-4" />
                <span>{errors.name}</span>
              </div>
            )}
          </div>

          <div>
            <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-2">
              <Mail className="inline w-4 h-4 mr-1" />
              Email Address
            </label>
            <input
              type="email"
              id="email"
              value={customerInfo.email}
              onChange={(e) => handleCustomerInfoChange('email', e.target.value)}
              placeholder="john@example.com"
              disabled={isProcessing}
              className="input-field"
            />
            {errors.email && (
              <div className="error-message">
                <AlertCircle className="w-4 h-4" />
                <span>{errors.email}</span>
              </div>
            )}
          </div>

          <div>
            <label htmlFor="phone" className="block text-sm font-medium text-gray-700 mb-2">
              <Phone className="inline w-4 h-4 mr-1" />
              Phone Number
            </label>
            <input
              type="tel"
              id="phone"
              value={customerInfo.phone}
              onChange={(e) => handleCustomerInfoChange('phone', e.target.value)}
              placeholder="(555) 123-4567"
              disabled={isProcessing}
              className="input-field"
            />
            {errors.phone && (
              <div className="error-message">
                <AlertCircle className="w-4 h-4" />
                <span>{errors.phone}</span>
              </div>
            )}
          </div>
        </div>

        {/* Card Information */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            <CreditCard className="inline w-4 h-4 mr-1" />
            Card Information
          </label>
          <div className="border-2 border-gray-300 rounded-lg p-4 focus-within:border-primary-500 focus-within:ring-2 focus-within:ring-primary-200 transition-all">
            <CardElement
              options={CARD_ELEMENT_OPTIONS}
              onChange={(e) => setCardComplete(e.complete)}
            />
          </div>
        </div>

        {/* Security Badge */}
        <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
          <div className="flex items-center gap-3">
            <Lock className="w-5 h-5 text-green-600" />
            <div className="text-sm text-gray-700">
              <p className="font-medium">Secure Payment</p>
              <p className="text-gray-600">
                Your payment information is encrypted and secure. We never store your card details.
              </p>
            </div>
          </div>
        </div>

        {/* Terms */}
        <div className="text-xs text-gray-600">
          <p>
            By completing this booking, you agree to our{' '}
            <a href="#" className="text-primary-600 hover:underline">Terms of Service</a>
            {' '}and{' '}
            <a href="#" className="text-primary-600 hover:underline">Privacy Policy</a>.
            Payment will be charged immediately upon confirmation.
          </p>
        </div>

        {/* Navigation Buttons */}
        <div className="flex justify-between pt-4">
          <button
            type="button"
            onClick={prevStep}
            disabled={isProcessing}
            className="btn-secondary"
          >
            ← Back
          </button>
          <button
            type="submit"
            disabled={isProcessing || !stripe || !cardComplete}
            className="btn-primary flex items-center gap-2"
          >
            {isProcessing ? (
              <>
                <Loader className="w-5 h-5 animate-spin" />
                Processing Payment...
              </>
            ) : (
              <>
                <Lock className="w-4 h-4" />
                Pay {formatCurrency(formData.estimate.total)}
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
};

const Step6Payment = (props) => {
  return (
    <Elements stripe={stripePromise}>
      <PaymentForm {...props} />
    </Elements>
  );
};

export default Step6Payment;

// customer-portal/src/components/steps/Step6Payment.svelte
<script>
  import { CreditCard, Loader, Check, AlertCircle, Lock } from 'lucide-svelte';
  import { fade, fly, scale } from 'svelte/transition';
  import { onMount } from 'svelte';
  import { formData, isLoading, error, prevStep, resetForm } from '../../stores/bookingStore';
  import { api } from '../../services/api';
  import { loadStripe } from '@stripe/stripe-js';
  
  const STRIPE_PUBLIC_KEY = import.meta.env.VITE_STRIPE_PUBLIC_KEY || 'pk_test_51HK...'; // Use test key

  let stripe = null;
  let cardElement = null;
  let bookingId = null;
  let paymentSuccess = false;
  let processingPayment = false;
  let cardholderName = $formData.customerInfo.name || '';
  let cardError = '';

  onMount(async () => {
    // Load Stripe
    stripe = await loadStripe(STRIPE_PUBLIC_KEY);
    
    if (stripe) {
      const elements = stripe.elements();
      cardElement = elements.create('card', {
        style: {
          base: {
            fontSize: '16px',
            color: '#1e293b',
            '::placeholder': {
              color: '#94a3b8',
            },
          },
          invalid: {
            color: '#ef4444',
          },
        },
      });
      
      cardElement.mount('#card-element');
      
      cardElement.on('change', (event) => {
        cardError = event.error ? event.error.message : '';
      });
    }

    // Create booking
    await createBooking();
  });

  async function createBooking() {
    try {
      const result = await api.createBooking({
        address: $formData.address,
        addressDetails: $formData.addressDetails,
        itemCategory: $formData.itemCategory,
        itemDescription: $formData.itemDescription,
        quantity: $formData.quantity,
        photoUrls: $formData.photoUrls,
        selectedDate: $formData.selectedDate,
        selectedTime: $formData.selectedTime,
        estimate: $formData.estimate,
        customerInfo: $formData.customerInfo,
        totalAmount: $formData.estimate?.total || 0,
      });

      bookingId = result.bookingId || 'BOOK-' + Date.now();
    } catch (err) {
      error.set('Failed to create booking: ' + err.message);
    }
  }

  async function handlePayment(e) {
    e.preventDefault();

    if (!cardholderName.trim()) {
      cardError = 'Cardholder name is required';
      return;
    }

    if (!stripe || !cardElement) {
      error.set('Payment system not loaded. Please refresh the page.');
      return;
    }

    processingPayment = true;
    error.set(null);
    cardError = '';

    try {
      // Create payment intent
      const { clientSecret } = await api.createPaymentIntent(
        bookingId,
        $formData.estimate.total
      );

      // Confirm payment
      const { error: stripeError, paymentIntent } = await stripe.confirmCardPayment(
        clientSecret,
        {
          payment_method: {
            card: cardElement,
            billing_details: {
              name: cardholderName,
              email: $formData.customerInfo.email,
            },
          },
        }
      );

      if (stripeError) {
        cardError = stripeError.message;
      } else if (paymentIntent.status === 'succeeded') {
        // Confirm with backend
        await api.confirmPayment(paymentIntent.id, bookingId);
        paymentSuccess = true;
      }
    } catch (err) {
      error.set(err.message);
    } finally {
      processingPayment = false;
    }
  }

  function handleNewBooking() {
    resetForm();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
</script>

{#if paymentSuccess}
  <!-- Success Screen -->
  <div class="card text-center" in:scale={{ duration: 500 }}>
    <div class="mb-6">
      <div class="w-20 h-20 bg-cta-100 rounded-full flex items-center justify-center mx-auto mb-4" in:scale={{ delay: 200, duration: 500 }}>
        <Check class="w-10 h-10 text-cta-600" />
      </div>
      <h2 class="text-3xl font-bold text-gray-900 font-heading mb-2">Booking Confirmed!</h2>
      <p class="text-gray-600">
        Your junk removal has been scheduled successfully.
      </p>
    </div>

    <div class="bg-gradient-to-br from-primary-50 to-indigo-50 rounded-xl p-6 mb-6 text-left">
      <h3 class="font-semibold text-gray-900 mb-3">Booking Details</h3>
      <div class="space-y-2 text-sm">
        <div class="flex justify-between">
          <span class="text-gray-600">Booking ID:</span>
          <span class="font-mono font-semibold text-primary-600">{bookingId}</span>
        </div>
        <div class="flex justify-between">
          <span class="text-gray-600">Total Amount:</span>
          <span class="font-semibold text-gray-900">${$formData.estimate.total.toFixed(2)}</span>
        </div>
        <div class="flex justify-between">
          <span class="text-gray-600">Scheduled:</span>
          <span class="font-semibold text-gray-900">{$formData.selectedTime}</span>
        </div>
      </div>
    </div>

    <div class="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6 text-left">
      <h4 class="font-semibold text-blue-900 mb-2">📧 Confirmation Email Sent</h4>
      <p class="text-sm text-blue-800">
        We've sent a confirmation email to <strong>{$formData.customerInfo.email}</strong> with 
        your booking details and what to expect on the day of service.
      </p>
    </div>

    <div class="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6 text-left">
      <h4 class="font-semibold text-yellow-900 mb-2">📱 Day of Service</h4>
      <ul class="text-sm text-yellow-800 space-y-1">
        <li>• We'll text you 30 minutes before arrival</li>
        <li>• Our crew will confirm the final price on-site</li>
        <li>• Payment is secured, no additional charges</li>
        <li>• We'll handle all the heavy lifting!</li>
      </ul>
    </div>

    <div class="bg-emerald-50 border border-emerald-200 rounded-lg p-4 mb-6 text-left">
      <h4 class="font-semibold text-emerald-900 mb-2">Track Your Booking</h4>
      <p class="text-sm text-emerald-800 mb-3">
        Follow your pickup in real-time once a driver is assigned.
      </p>
      <a
        href="?track={bookingId}"
        class="inline-flex items-center gap-2 bg-emerald-600 text-white px-4 py-2 rounded-lg hover:bg-emerald-700 transition-colors text-sm font-medium"
      >
        Track Live
      </a>
    </div>

    <div class="flex flex-col sm:flex-row gap-3">
      <button
        on:click={handleNewBooking}
        class="btn-primary flex-1"
      >
        Book Another Pickup
      </button>
      <button
        on:click={() => window.print()}
        class="btn-secondary flex-1"
      >
        Print Confirmation
      </button>
    </div>
  </div>
{:else}
  <!-- Payment Form -->
  <div class="card" in:fly={{ x: 20, duration: 300 }}>
    <div class="mb-6">
      <div class="flex items-center gap-3 mb-2">
        <div class="bg-cta-100 p-2 rounded-lg">
          <CreditCard class="w-6 h-6 text-cta-600" />
        </div>
        <h2 class="text-2xl font-bold text-gray-900 font-heading">Secure Payment</h2>
      </div>
      <p class="text-gray-600">
        Complete your booking with a secure payment.
      </p>
    </div>

    <!-- Payment Summary -->
    <div class="bg-gradient-to-br from-cta-50 to-emerald-50 rounded-xl p-6 mb-6 border-2 border-cta-200">
      <div class="flex justify-between items-center">
        <div>
          <p class="text-gray-600 text-sm">Total Amount Due</p>
          <p class="text-3xl font-bold text-cta-600">${$formData.estimate.total.toFixed(2)}</p>
        </div>
        <div class="text-right">
          <p class="text-gray-600 text-sm">Booking ID</p>
          <p class="font-mono text-sm font-semibold text-gray-900">{bookingId || 'Generating...'}</p>
        </div>
      </div>
    </div>

    <form on:submit={handlePayment} class="space-y-6">
      <!-- Cardholder Name -->
      <div>
        <label for="cardholder-name" class="block text-sm font-medium text-gray-700 mb-2">
          Cardholder Name
        </label>
        <input
          type="text"
          id="cardholder-name"
          bind:value={cardholderName}
          placeholder="John Doe"
          disabled={processingPayment}
          class="input-field"
        />
      </div>

      <!-- Card Element -->
      <div>
        <div class="block text-sm font-medium text-gray-700 mb-2">
          Card Information
        </div>
        <div 
          id="card-element" 
          class="input-field"
          class:border-red-500={cardError}
        ></div>
        {#if cardError}
          <div class="error-message mt-2" transition:fly={{ y: -10, duration: 200 }}>
            <AlertCircle class="w-4 h-4" />
            <span>{cardError}</span>
          </div>
        {/if}
      </div>

      <!-- Security Notice -->
      <div class="bg-gray-50 border border-gray-200 rounded-lg p-4 flex gap-3">
        <Lock class="w-5 h-5 text-gray-600 mt-0.5 flex-shrink-0" />
        <div class="text-sm text-gray-700">
          <p class="font-semibold mb-1">🔒 Secure Payment</p>
          <p>
            Your payment information is encrypted and secure. We use Stripe for payment processing 
            and never store your card details.
          </p>
        </div>
      </div>

      <!-- Test Card Info (only in development) -->
      <div class="bg-blue-50 border border-blue-200 rounded-lg p-4">
        <p class="text-sm text-blue-900 font-semibold mb-1">💳 Test Mode</p>
        <p class="text-xs text-blue-800">
          Use card: <strong>4242 4242 4242 4242</strong> | Exp: Any future date | CVC: Any 3 digits
        </p>
      </div>

      <!-- Navigation -->
      <div class="flex justify-between pt-4">
        <button
          type="button"
          on:click={prevStep}
          disabled={processingPayment}
          class="btn-secondary"
        >
          ← Back
        </button>
        
        <button
          type="submit"
          disabled={processingPayment || !bookingId}
          class="btn-primary flex items-center gap-2"
        >
          {#if processingPayment}
            <Loader class="w-5 h-5 animate-spin" />
            <span>Processing...</span>
          {:else}
            <Lock class="w-4 h-4" />
            <span>Pay ${$formData.estimate.total.toFixed(2)}</span>
          {/if}
        </button>
      </div>
    </form>
  </div>
{/if}
