// customer-portal-react/src/components/BookingFlow/Step6Payment.jsx
import React, { useState, useEffect, useRef } from 'react';
import { loadStripe } from '@stripe/stripe-js';
import { Elements, CardElement, PaymentRequestButtonElement, useStripe, useElements } from '@stripe/react-stripe-js';
import { CreditCard, Lock, Loader, CheckCircle, AlertCircle, Mail, Phone, User, Smartphone } from 'lucide-react';
import { validateEmail, validatePhone, formatPhoneNumber, formatCurrency } from '../../utils/validation';
import { api } from '../../services/api';

// Initialize Stripe
const stripePromise = loadStripe(import.meta.env.VITE_STRIPE_PUBLIC_KEY || 'pk_test_placeholder');

const CARD_ELEMENT_OPTIONS = {
  style: {
    base: {
      fontSize: '16px',
      color: '#1f2937',
      fontFamily: 'Inter, system-ui, sans-serif',
      '::placeholder': {
        color: '#9ca3af',
      },
    },
    invalid: {
      color: '#dc2626',
      iconColor: '#dc2626',
    },
  },
};

const PaymentForm = ({ formData, updateCustomerInfo, prevStep, setError, resetForm }) => {
  const stripe = useStripe();
  const elements = useElements();

  const [isProcessing, setIsProcessing] = useState(false);
  const [paymentSuccess, setPaymentSuccess] = useState(false);
  const [bookingId, setBookingId] = useState(null);

  const [customerInfo, setCustomerInfo] = useState({
    name: formData.customerInfo?.name || '',
    email: formData.customerInfo?.email || '',
    phone: formData.customerInfo?.phone || '',
  });

  const [errors, setErrors] = useState({});
  const [cardComplete, setCardComplete] = useState(false);

  // Apple Pay / Google Pay
  const [paymentRequest, setPaymentRequest] = useState(null);
  const [canMakePayment, setCanMakePayment] = useState(null);
  const paymentRequestRef = useRef(null);

  useEffect(() => {
    if (!stripe || !formData.estimate?.total) return;

    const pr = stripe.paymentRequest({
      country: 'US',
      currency: 'usd',
      total: {
        label: 'JunkOS Junk Removal',
        amount: Math.round(formData.estimate.total * 100),
      },
      requestPayerName: true,
      requestPayerEmail: true,
      requestPayerPhone: true,
    });

    pr.canMakePayment().then((result) => {
      if (result) {
        setCanMakePayment(result);
        setPaymentRequest(pr);
        paymentRequestRef.current = pr;
      }
    });

    pr.on('paymentmethod', async (ev) => {
      try {
        // Extract payer info from Apple Pay / Google Pay
        const payerName = ev.payerName || '';
        const payerEmail = ev.payerEmail || '';
        const payerPhone = ev.payerPhone || '';

        // 1. Create booking
        const bookingData = {
          ...formData,
          customerInfo: { name: payerName, email: payerEmail, phone: payerPhone },
          totalAmount: formData.estimate.total,
        };
        const bookingResult = await api.createBooking(bookingData);
        const newBookingId = bookingResult.bookingId;

        // 2. Create payment intent
        const piResult = await api.createPaymentIntent(newBookingId, formData.estimate.total);

        // 3. Confirm with the payment method from Apple Pay / Google Pay
        const { error, paymentIntent } = await stripe.confirmCardPayment(
          piResult.clientSecret,
          { payment_method: ev.paymentMethod.id },
          { handleActions: false }
        );

        if (error) {
          ev.complete('fail');
          setError(error.message);
          return;
        }

        if (paymentIntent.status === 'requires_action') {
          const { error: actionError } = await stripe.confirmCardPayment(piResult.clientSecret);
          if (actionError) {
            ev.complete('fail');
            setError(actionError.message);
            return;
          }
        }

        ev.complete('success');

        // 4. Confirm in backend
        await api.confirmPayment(paymentIntent.id, newBookingId);

        // Update UI
        setBookingId(newBookingId);
        setPaymentSuccess(true);
        updateCustomerInfo('name', payerName);
        updateCustomerInfo('email', payerEmail);
        updateCustomerInfo('phone', payerPhone);
        setCustomerInfo({ name: payerName, email: payerEmail, phone: payerPhone });
      } catch (err) {
        ev.complete('fail');
        setError(err.message || 'Payment failed. Please try again.');
      }
    });

    return () => {
      paymentRequestRef.current = null;
    };
  }, [stripe, formData.estimate?.total]);

  const handleCustomerInfoChange = (field, value) => {
    setCustomerInfo((prev) => ({
      ...prev,
      [field]: field === 'phone' ? formatPhoneNumber(value) : value,
    }));
    
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: '' }));
    }
  };

  const validateCustomerInfo = () => {
    const newErrors = {};

    if (!customerInfo.name || customerInfo.name.trim().length < 2) {
      newErrors.name = 'Please enter your full name';
    }

    const emailError = validateEmail(customerInfo.email);
    if (emailError) {
      newErrors.email = emailError;
    }

    const phoneError = validatePhone(customerInfo.phone);
    if (phoneError) {
      newErrors.phone = phoneError;
    }

    return newErrors;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    // Validate customer info
    const validationErrors = validateCustomerInfo();
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    if (!stripe || !elements || !cardComplete) {
      setError('Please complete your payment information');
      return;
    }

    setIsProcessing(true);
    setError(null);

    try {
      // 1. Create booking in backend
      const bookingData = {
        ...formData,
        customerInfo,
        totalAmount: formData.estimate.total,
      };

      const bookingResult = await api.createBooking(bookingData);
      const newBookingId = bookingResult.bookingId;
      setBookingId(newBookingId);

      // 2. Create payment intent
      const paymentIntentResult = await api.createPaymentIntent(
        newBookingId,
        formData.estimate.total
      );

      const clientSecret = paymentIntentResult.clientSecret;

      // 3. Confirm payment with Stripe
      const cardElement = elements.getElement(CardElement);
      const { error, paymentIntent } = await stripe.confirmCardPayment(clientSecret, {
        payment_method: {
          card: cardElement,
          billing_details: {
            name: customerInfo.name,
            email: customerInfo.email,
            phone: customerInfo.phone,
          },
        },
      });

      if (error) {
        throw new Error(error.message);
      }

      // 4. Confirm payment in backend
      await api.confirmPayment(paymentIntent.id, newBookingId);

      // Success!
      setPaymentSuccess(true);
      
      // Save customer info
      updateCustomerInfo('name', customerInfo.name);
      updateCustomerInfo('email', customerInfo.email);
      updateCustomerInfo('phone', customerInfo.phone);

    } catch (err) {
      setError(err.message || 'Payment failed. Please try again.');
      console.error('Payment error:', err);
    } finally {
      setIsProcessing(false);
    }
  };

  if (paymentSuccess) {
    return (
      <div className="card animate-fade-in">
        <div className="text-center pt-8 pb-4">
          <div className="inline-flex items-center justify-center w-20 h-20 bg-green-100 rounded-full mb-5">
            <CheckCircle className="w-12 h-12 text-green-600" />
          </div>

          <h2 className="text-2xl font-bold text-gray-900 mb-2">
            Your pickup is booked.
          </h2>

          <p className="text-gray-600 mb-1">
            This is a no-obligation service — you'll know the exact cost before we start.
          </p>

          <p className="text-sm text-gray-500 mb-6">
            A confirmation email has been sent to <strong className="text-gray-700">{customerInfo.email}</strong>.
          </p>
        </div>

        {/* Booking summary */}
        <div className="bg-gray-50 rounded-lg p-5 mb-6">
          <div className="grid grid-cols-2 gap-3 text-sm">
            <div>
              <span className="text-gray-500">Booking ID</span>
              <p className="font-medium text-gray-900">{bookingId?.slice(0, 8)}</p>
            </div>
            <div>
              <span className="text-gray-500">Amount</span>
              <p className="font-medium text-gray-900">{formatCurrency(formData.estimate.total)}</p>
            </div>
            <div>
              <span className="text-gray-500">Date</span>
              <p className="font-medium text-gray-900">
                {formData.selectedDate
                  ? new Date(formData.selectedDate).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })
                  : 'TBD'}
              </p>
            </div>
            <div>
              <span className="text-gray-500">Time</span>
              <p className="font-medium text-gray-900">{formData.selectedTime || 'TBD'}</p>
            </div>
          </div>
        </div>

        {/* What happens next */}
        <div className="mb-6">
          <h3 className="font-semibold text-gray-900 mb-4">What happens next?</h3>

          <div className="space-y-5">
            {/* Step 1 */}
            <div className="flex gap-4">
              <div className="flex-shrink-0 w-8 h-8 bg-primary-100 text-primary-700 rounded-full flex items-center justify-center font-bold text-sm">
                1
              </div>
              <div>
                <p className="font-semibold text-gray-900">We'll call to confirm your appointment</p>
                <p className="text-sm text-gray-600 mt-0.5">
                  You'll get a call 15–30 minutes before your scheduled window. We'll confirm the timing and go over any details.
                </p>
              </div>
            </div>

            {/* Step 2 */}
            <div className="flex gap-4">
              <div className="flex-shrink-0 w-8 h-8 bg-primary-100 text-primary-700 rounded-full flex items-center justify-center font-bold text-sm">
                2
              </div>
              <div>
                <p className="font-semibold text-gray-900">We'll assess your items and give an exact price</p>
                <p className="text-sm text-gray-600 mt-0.5">
                  Our crew will look at everything on-site and provide an all-inclusive price. No obligation — if it doesn't work for you, there's no charge.
                </p>
              </div>
            </div>

            {/* Step 3 */}
            <div className="flex gap-4">
              <div className="flex-shrink-0 w-8 h-8 bg-primary-100 text-primary-700 rounded-full flex items-center justify-center font-bold text-sm">
                3
              </div>
              <div>
                <p className="font-semibold text-gray-900">We take care of everything, hassle-free</p>
                <p className="text-sm text-gray-600 mt-0.5">
                  Once you give the go-ahead, we'll remove your items, sweep up the area, and you're done. It's that easy.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Reminder note */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
          <div className="flex gap-3">
            <Mail className="w-5 h-5 text-blue-600 mt-0.5 flex-shrink-0" />
            <p className="text-sm text-blue-900">
              We'll send you a reminder <strong>24 hours before</strong> your appointment with everything you need to know.
            </p>
          </div>
        </div>

        <button
          onClick={resetForm}
          className="btn-primary w-full"
        >
          Book Another Pickup
        </button>
      </div>
    );
  }

  return (
    <div className="card animate-fade-in">
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="bg-primary-100 p-2 rounded-lg">
            <CreditCard className="w-6 h-6 text-primary-600" />
          </div>
          <h2 className="text-2xl font-bold text-gray-900">Payment Details</h2>
        </div>
        <p className="text-gray-600">
          Complete your booking with secure payment.
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Amount Due */}
        <div className="bg-primary-50 border-2 border-primary-200 rounded-lg p-5">
          <div className="flex justify-between items-center">
            <span className="text-lg font-medium text-gray-900">Amount Due</span>
            <span className="text-3xl font-bold text-primary-600">
              {formatCurrency(formData.estimate.total)}
            </span>
          </div>
        </div>

        {/* Apple Pay / Google Pay */}
        {paymentRequest && canMakePayment && (
          <>
            <div>
              <PaymentRequestButtonElement
                options={{
                  paymentRequest,
                  style: {
                    paymentRequestButton: {
                      type: 'default',
                      theme: 'dark',
                      height: '48px',
                    },
                  },
                }}
              />
            </div>
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-gray-300"></div>
              </div>
              <div className="relative flex justify-center text-sm">
                <span className="bg-white px-4 text-gray-500">or pay with card</span>
              </div>
            </div>
          </>
        )}

        {/* Customer Information */}
        <div className="space-y-4">
          <h3 className="font-semibold text-gray-900">Contact Information</h3>
          
          <div>
            <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-2">
              <User className="inline w-4 h-4 mr-1" />
              Full Name
            </label>
            <input
              type="text"
              id="name"
              value={customerInfo.name}
              onChange={(e) => handleCustomerInfoChange('name', e.target.value)}
              placeholder="John Doe"
              disabled={isProcessing}
              className="input-field"
            />
            {errors.name && (
              <div className="error-message">
                <AlertCircle className="w-4 h-4" />
                <span>{errors.name}</span>
              </div>
            )}
          </div>

          <div>
            <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-2">
              <Mail className="inline w-4 h-4 mr-1" />
              Email Address
            </label>
            <input
              type="email"
              id="email"
              value={customerInfo.email}
              onChange={(e) => handleCustomerInfoChange('email', e.target.value)}
              placeholder="john@example.com"
              disabled={isProcessing}
              className="input-field"
            />
            {errors.email && (
              <div className="error-message">
                <AlertCircle className="w-4 h-4" />
                <span>{errors.email}</span>
              </div>
            )}
          </div>

          <div>
            <label htmlFor="phone" className="block text-sm font-medium text-gray-700 mb-2">
              <Phone className="inline w-4 h-4 mr-1" />
              Phone Number
            </label>
            <input
              type="tel"
              id="phone"
              value={customerInfo.phone}
              onChange={(e) => handleCustomerInfoChange('phone', e.target.value)}
              placeholder="(555) 123-4567"
              disabled={isProcessing}
              className="input-field"
            />
            {errors.phone && (
              <div className="error-message">
                <AlertCircle className="w-4 h-4" />
                <span>{errors.phone}</span>
              </div>
            )}
          </div>
        </div>

        {/* Card Information */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            <CreditCard className="inline w-4 h-4 mr-1" />
            Card Information
          </label>
          <div className="border-2 border-gray-300 rounded-lg p-4 focus-within:border-primary-500 focus-within:ring-2 focus-within:ring-primary-200 transition-all">
            <CardElement
              options={CARD_ELEMENT_OPTIONS}
              onChange={(e) => setCardComplete(e.complete)}
            />
          </div>
        </div>

        {/* Security Badge */}
        <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
          <div className="flex items-center gap-3">
            <Lock className="w-5 h-5 text-green-600" />
            <div className="text-sm text-gray-700">
              <p className="font-medium">Secure Payment</p>
              <p className="text-gray-600">
                Your payment information is encrypted and secure. We never store your card details.
              </p>
            </div>
          </div>
        </div>

        {/* Terms */}
        <div className="text-xs text-gray-600">
          <p>
            By completing this booking, you agree to our{' '}
            <a href="#" className="text-primary-600 hover:underline">Terms of Service</a>
            {' '}and{' '}
            <a href="#" className="text-primary-600 hover:underline">Privacy Policy</a>.
            Payment will be charged immediately upon confirmation.
          </p>
        </div>

        {/* Navigation Buttons */}
        <div className="flex justify-between pt-4">
          <button
            type="button"
            onClick={prevStep}
            disabled={isProcessing}
            className="btn-secondary"
          >
            ← Back
          </button>
          <button
            type="submit"
            disabled={isProcessing || !stripe || !cardComplete}
            className="btn-primary flex items-center gap-2"
          >
            {isProcessing ? (
              <>
                <Loader className="w-5 h-5 animate-spin" />
                Processing Payment...
              </>
            ) : (
              <>
                <Lock className="w-4 h-4" />
                Pay {formatCurrency(formData.estimate.total)}
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
};

const Step6Payment = (props) => {
  return (
    <Elements stripe={stripePromise}>
      <PaymentForm {...props} />
    </Elements>
  );
};

export default Step6Payment;

// customer-portal/src/components/steps/Step6Payment.svelte
<script>
  import { CreditCard, Loader, Check, AlertCircle, Lock, Truck } from 'lucide-svelte';
  import { fade, fly, scale } from 'svelte/transition';
  import { formData, isLoading, error, prevStep, resetForm } from '../../stores/bookingStore';
  import { api } from '../../services/api';
  import { loadStripe } from '@stripe/stripe-js';

  const STRIPE_PUBLIC_KEY = import.meta.env.VITE_STRIPE_PUBLIC_KEY || 'pk_test_51SyjNcIowMGOXFMncmnEP1ZcWi8XX7KdPuQhPCMbN1bMRb4NgH1rmLeB4SGlhy9aD9FMrBJQ2QcCsZFxJ98wtTCA00i4WfgNq6';

  let stripe = null;
  let cardElement = null;
  let cardMountEl = null;
  let applePayMountEl = null;
  let bookingId = null;
  let paymentSuccess = false;
  let processingPayment = false;
  let cardholderName = $formData.customerInfo.name || '';
  let cardError = '';
  let initialized = false;
  let canMakePayment = false;
  let paymentRequest = null;

  // Use reactive statement instead of onMount (fixes {#key} + svelte:component issue)
  $: if (cardMountEl && !initialized) {
    initialized = true;
    initPayment();
  }

  async function initPayment() {
    // Load Stripe
    stripe = await loadStripe(STRIPE_PUBLIC_KEY);

    if (stripe && cardMountEl) {
      const elements = stripe.elements();
      cardElement = elements.create('card', {
        style: {
          base: {
            fontFamily: '"DM Sans", system-ui, sans-serif',
            fontSize: '16px',
            color: '#3f3931',
            '::placeholder': {
              color: '#b8b0a3',
            },
          },
          invalid: {
            color: '#ef4444',
          },
        },
      });

      cardElement.mount(cardMountEl);

      cardElement.on('change', (event) => {
        cardError = event.error ? event.error.message : '';
      });

      // Set up Apple Pay / Google Pay
      setupPaymentRequest(stripe, elements);
    }

    // Create booking
    await createBooking();
  }

  async function setupPaymentRequest(stripe, elements) {
    const total = $formData.estimate?.total || 0;
    if (!total) return;

    const pr = stripe.paymentRequest({
      country: 'US',
      currency: 'usd',
      total: {
        label: 'JunkOS Junk Removal',
        amount: Math.round(total * 100),
      },
      requestPayerName: true,
      requestPayerEmail: true,
      requestPayerPhone: true,
    });

    const result = await pr.canMakePayment();
    if (result) {
      canMakePayment = true;
      paymentRequest = pr;

      const prButton = elements.create('paymentRequestButton', {
        paymentRequest: pr,
        style: {
          paymentRequestButton: {
            type: 'default',
            theme: 'dark',
            height: '48px',
          },
        },
      });

      // Mount after a tick to ensure the DOM element exists
      setTimeout(() => {
        if (applePayMountEl) {
          prButton.mount(applePayMountEl);
        }
      }, 50);

      pr.on('paymentmethod', async (ev) => {
        try {
          const payerName = ev.payerName || '';
          const payerEmail = ev.payerEmail || '';

          // Ensure we have a booking
          if (!bookingId) {
            ev.complete('fail');
            error.set('No booking found. Please go back and try again.');
            return;
          }

          // Create payment intent
          const piResult = await api.createPaymentIntent(bookingId, total);

          // Confirm with the payment method from Apple Pay / Google Pay
          const { error: confirmError, paymentIntent } = await stripe.confirmCardPayment(
            piResult.clientSecret,
            { payment_method: ev.paymentMethod.id },
            { handleActions: false }
          );

          if (confirmError) {
            ev.complete('fail');
            cardError = confirmError.message;
          } else {
            ev.complete('success');
            if (paymentIntent.status === 'succeeded') {
              await api.confirmPayment(paymentIntent.id, bookingId);
              paymentSuccess = true;
            }
          }
        } catch (err) {
          ev.complete('fail');
          error.set(err.message || 'Payment failed');
        }
      });
    }
  }

  async function createBooking() {
    try {
      // Extract a 24h time string from the selected time slot (e.g. "8:00 AM - 10:00 AM" -> "08:00")
      let timeForBackend = $formData.selectedTime;
      if (typeof timeForBackend === 'string' && timeForBackend.includes('AM') || typeof timeForBackend === 'string' && timeForBackend.includes('PM')) {
        const match = timeForBackend.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)/i);
        if (match) {
          let hours = parseInt(match[1], 10);
          const minutes = match[2];
          const period = match[3].toUpperCase();
          if (period === 'PM' && hours !== 12) hours += 12;
          if (period === 'AM' && hours === 12) hours = 0;
          timeForBackend = `${String(hours).padStart(2, '0')}:${minutes}`;
        }
      }

      const result = await api.createBooking({
        address: $formData.address,
        addressDetails: $formData.addressDetails,
        itemCategory: $formData.itemCategory,
        itemDescription: $formData.itemDescription,
        quantity: $formData.quantity,
        photoUrls: $formData.photoUrls,
        selectedDate: $formData.selectedDate,
        selectedTime: timeForBackend,
        estimate: $formData.estimate,
        customerInfo: $formData.customerInfo,
        totalAmount: $formData.estimate?.total || 0,
      });

      bookingId = result.bookingId || result.booking_id || null;
      if (!bookingId) {
        console.error('Booking created but no bookingId returned:', result);
        error.set('Booking was created but we could not retrieve its ID. Please contact support.');
      }
    } catch (err) {
      console.error('Failed to create booking:', err);
      error.set('Could not create your booking. Please check your connection and try again.');
    }
  }

  async function handlePayment(e) {
    e.preventDefault();

    if (!cardholderName.trim()) {
      cardError = 'Cardholder name is required';
      return;
    }

    if (!stripe || !cardElement) {
      error.set('Payment system not loaded. Please refresh the page.');
      return;
    }

    if (!bookingId) {
      error.set('No booking found. Please go back and try again.');
      return;
    }

    processingPayment = true;
    error.set(null);
    cardError = '';

    try {
      // Create payment intent
      const { clientSecret } = await api.createPaymentIntent(
        bookingId,
        $formData.estimate?.total || 0
      );

      // Confirm payment
      const { error: stripeError, paymentIntent } = await stripe.confirmCardPayment(
        clientSecret,
        {
          payment_method: {
            card: cardElement,
            billing_details: {
              name: cardholderName,
              email: $formData.customerInfo.email,
            },
          },
        }
      );

      if (stripeError) {
        cardError = stripeError.message;
      } else if (paymentIntent.status === 'succeeded') {
        // Confirm with backend
        try {
          await api.confirmPayment(paymentIntent.id, bookingId);
        } catch (_) {
          // Backend confirmation failed but payment succeeded
        }
        paymentSuccess = true;
      }
    } catch (err) {
      error.set(err.message || 'Payment failed. Please try again.');
    } finally {
      processingPayment = false;
    }
  }

  function handleNewBooking() {
    resetForm();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
</script>

{#if paymentSuccess}
  <!-- Success Screen -->
  <div class="card text-center" in:scale={{ duration: 500 }}>
    <div class="mb-8">
      <div class="w-16 h-16 bg-primary-100 rounded-2xl flex items-center justify-center mx-auto mb-5" in:scale={{ delay: 200, duration: 500 }}>
        <Check class="w-8 h-8 text-primary-600" />
      </div>
      <h2 class="text-3xl font-bold text-warm-900 font-heading mb-2">You're all set!</h2>
      <p class="text-warm-500">
        Your pickup has been scheduled.
      </p>
    </div>

    <div class="bg-warm-50 rounded-xl p-5 mb-6 text-left border border-warm-200">
      <div class="space-y-2.5 text-sm">
        <div class="flex justify-between">
          <span class="text-warm-500">Booking ID</span>
          <span class="font-mono font-semibold text-primary-700">{bookingId}</span>
        </div>
        <div class="flex justify-between">
          <span class="text-warm-500">Total</span>
          <span class="font-heading font-bold text-warm-900">${($formData.estimate?.total || 0).toFixed(2)}</span>
        </div>
        <div class="flex justify-between">
          <span class="text-warm-500">When</span>
          <span class="font-medium text-warm-800">{$formData.selectedTime}</span>
        </div>
      </div>
    </div>

    <div class="info-box-emerald mb-6 text-left">
      <Truck class="w-4 h-4 text-primary-600 mt-0.5 flex-shrink-0" />
      <div>
        <p class="font-semibold text-sm mb-1">What happens next</p>
        <ul class="text-xs space-y-1 opacity-80">
          <li>We'll text you 30 min before arrival</li>
          <li>Crew confirms the price on-site</li>
          <li>We handle all the heavy lifting</li>
        </ul>
      </div>
    </div>

    <div class="info-box-blue mb-6 text-left">
      <Check class="w-4 h-4 text-blue-600 mt-0.5 flex-shrink-0" />
      <div>
        <p class="font-semibold text-sm mb-0.5">Confirmation sent</p>
        <p class="text-xs opacity-80">
          Check <strong>{$formData.customerInfo.email}</strong> for details.
        </p>
      </div>
    </div>

    <a
      href="?track={bookingId}"
      class="btn-primary w-full flex items-center justify-center gap-2 mb-3"
    >
      Track Your Pickup
      <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
        <line x1="5" y1="12" x2="19" y2="12"></line>
        <polyline points="12 5 19 12 12 19"></polyline>
      </svg>
    </a>

    <button
      on:click={handleNewBooking}
      class="btn-secondary w-full"
    >
      Book Another Pickup
    </button>
  </div>
{:else}
  <!-- Payment Form -->
  <div class="card">
    <div class="mb-8">
      <h2 class="text-2xl font-bold text-warm-900 font-heading mb-1">Complete Payment</h2>
      <p class="text-warm-500">
        Secure checkout powered by Stripe.
      </p>
    </div>

    <!-- Global Error Display -->
    {#if $error}
      <div class="bg-red-50 border border-red-200 rounded-xl p-4 mb-6 flex items-start gap-3" transition:fly={{ y: -10, duration: 200 }}>
        <AlertCircle class="w-5 h-5 text-red-500 mt-0.5 flex-shrink-0" />
        <div>
          <p class="text-sm font-semibold text-red-800">Something went wrong</p>
          <p class="text-xs text-red-600 mt-0.5">{$error}</p>
        </div>
      </div>
    {/if}

    <!-- Payment Summary -->
    <div class="bg-warm-50 rounded-xl p-5 mb-6 border border-warm-200">
      <div class="flex justify-between items-center">
        <div>
          <p class="text-xs text-warm-400 uppercase tracking-wider font-semibold">Total Due</p>
          <p class="text-3xl font-heading font-bold text-primary-600 mt-0.5">${($formData.estimate?.total || 0).toFixed(2)}</p>
        </div>
        <div class="text-right">
          <p class="text-xs text-warm-400 uppercase tracking-wider font-semibold">Booking</p>
          <p class="font-mono text-sm font-semibold text-warm-700 mt-0.5">{bookingId || '...'}</p>
        </div>
      </div>
    </div>

    <!-- Apple Pay / Google Pay -->
    {#if canMakePayment}
      <div class="mb-6">
        <div bind:this={applePayMountEl}></div>
        <div class="relative my-5">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-warm-200"></div>
          </div>
          <div class="relative flex justify-center text-xs">
            <span class="bg-white px-4 text-warm-400 uppercase tracking-wider font-medium">or pay with card</span>
          </div>
        </div>
      </div>
    {/if}

    <form on:submit={handlePayment} class="space-y-5">
      <!-- Cardholder Name -->
      <div>
        <label for="cardholder-name" class="block text-sm font-semibold text-warm-700 mb-1.5">
          Name on Card
        </label>
        <input
          type="text"
          id="cardholder-name"
          bind:value={cardholderName}
          placeholder="John Doe"
          disabled={processingPayment}
          class="input-field"
        />
      </div>

      <!-- Card Element -->
      <div>
        <label class="block text-sm font-semibold text-warm-700 mb-1.5">
          Card Details
        </label>
        <div
          bind:this={cardMountEl}
          id="card-element"
          class="input-field"
          class:border-red-400={cardError}
        ></div>
        {#if cardError}
          <div class="error-message mt-1.5" transition:fly={{ y: -10, duration: 200 }}>
            <AlertCircle class="w-4 h-4" />
            <span>{cardError}</span>
          </div>
        {/if}
      </div>

      <!-- Security Notice -->
      <div class="flex items-center gap-2 text-xs text-warm-400">
        <Lock class="w-3.5 h-3.5" />
        <span>Encrypted with SSL. We never store your card details.</span>
      </div>

      <!-- Test Card Info -->
      <div class="info-box-blue">
        <CreditCard class="w-4 h-4 text-blue-600 mt-0.5 flex-shrink-0" />
        <div>
          <p class="font-semibold text-sm mb-0.5">Test Mode</p>
          <p class="text-xs opacity-80">
            Use <span class="font-mono font-semibold">4242 4242 4242 4242</span> &middot; any future date &middot; any CVC
          </p>
        </div>
      </div>

      <!-- Navigation -->
      <div class="flex justify-between pt-2">
        <button
          type="button"
          on:click={prevStep}
          disabled={processingPayment}
          class="btn-secondary"
        >
          Back
        </button>

        <button
          type="submit"
          disabled={processingPayment || !bookingId}
          class="btn-primary flex items-center gap-2"
        >
          {#if processingPayment}
            <Loader class="w-5 h-5 animate-spin" />
            <span>Processing...</span>
          {:else}
            <Lock class="w-4 h-4" />
            <span>Pay ${($formData.estimate?.total || 0).toFixed(2)}</span>
          {/if}
        </button>
      </div>
    </form>
  </div>
{/if}
